name: Clash Config Testing – Enhanced

on:
  schedule:
    - cron: '0 0 * * *'          # Every day at 00:00 UTC
  workflow_dispatch:
    inputs:
      test_workers:
        description: 'Number of parallel test workers'
        required: false
        default: '20'
      test_timeout:
        description: 'Test timeout (seconds)'
        required: false
        default: '10'
  push:
    branches: [main]
    paths:
      - 'sub.txt'
      - 'scripts/**'
      - '.github/workflows/clash-config-test.yml'

jobs:
  test-configs:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
          echo "✓ Python dependencies installed"

      - name: Download and install Clash Meta
        run: |
          CLASH_VERSION="v1.18.0"
          CLASH_URL="https://github.com/MetaCubeX/mihomo/releases/download/${CLASH_VERSION}/mihomo-linux-amd64-${CLASH_VERSION}.gz"
          echo "📥 Downloading Clash Meta ${CLASH_VERSION}..."
          wget -q "${CLASH_URL}" -O clash.gz
          gunzip clash.gz && chmod +x clash
          mkdir -p ~/.local/bin
          mv clash ~/.local/bin/clash
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          ~/.local/bin/clash -v
          echo "✓ Clash Meta installed"

      - name: Download subscriptions
        id: download
        run: |
          cd scripts
          python download_subscriptions.py
          if [ -f "../temp_configs/parsed_proxies.json" ]; then
            PROXY_COUNT=$(python -c "import sys,json;print(len(json.load(sys.stdin)))" < ../temp_configs/parsed_proxies.json)
            echo "proxy_count=$PROXY_COUNT" >> $GITHUB_OUTPUT
            echo "✓ Downloaded $PROXY_COUNT proxies"
          else
            echo "✗ Download failed"
            exit 1
          fi
        continue-on-error: false

      - name: Test configs
        id: test
        env:
          TEST_WORKERS: ${{ github.event.inputs.test_workers || '20' }}
          TEST_TIMEOUT: ${{ github.event.inputs.test_timeout || '10' }}
        run: |
          cd scripts
          python test_configs.py
          if [ -f "../working_configs/metadata.json" ]; then
            WORKING=$(python -c "import sys,json;print(json.load(sys.stdin)['total_working'])" < ../working_configs/metadata.json)
            echo "working_count=$WORKING" >> $GITHUB_OUTPUT
            echo "✓ Found $WORKING working proxies"
          else
            echo "working_count=0" >> $GITHUB_OUTPUT
            echo "⚠ No working proxies found"
          fi
        continue-on-error: true

      - name: Generate detailed summary
        if: always()
        run: |
          {
            echo "# 🔍 Clash Config Test Results"
            echo ""
            echo "**Date:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            echo ""
          } >> $GITHUB_STEP_SUMMARY

          if [ -f "working_configs/metadata.json" ]; then
            TOTAL=$(python -c "import sys,json;print(json.load(sys.stdin)['total_working'])" < working_configs/metadata.json)
            AVG_LATENCY=$(python -c "import sys,json;print(json.load(sys.stdin)['latency']['average'])" < working_configs/metadata.json)
            {
              echo "## ✅ Test Successful"
              echo ""
              echo "### 📊 Statistics"
              echo ""
              echo "- **Total Working Proxies:** $TOTAL"
              echo "- **Average Latency:** ${AVG_LATENCY}ms"
              echo ""
              echo "### 📋 By Protocol"
            } >> $GITHUB_STEP_SUMMARY

            python -c "
data=json.load(sys.stdin)
for proto,count in sorted(data['by_protocol'].items(),key=lambda x:-x[1]):
    print(f'- **{proto}:** {count}')
            " < working_configs/metadata.json >> $GITHUB_STEP_SUMMARY

            {
              echo ""
              echo "### 📦 Output Files"
              echo ""
              echo "- \`working_configs/all_working.txt\` - All working proxies"
              echo "- \`working_configs/all_working_base64.txt\` - Base64 encoded"
              echo "- \`working_configs/clash_config.yaml\` - Ready-to-use Clash config"
              echo "- \`working_configs/by_protocol/\` - Grouped by protocol"
            } >> $GITHUB_STEP_SUMMARY

          elif [ -f "temp_configs/download_stats.json" ]; then
            DOWNLOADED=$(python -c "import sys,json;print(json.load(sys.stdin)['total_parsed'])" < temp_configs/download_stats.json)
            {
              echo "## ⚠️ Testing Failed"
              echo ""
              echo "Download completed but no proxies passed connectivity test."
              echo ""
              echo "- **Proxies Downloaded:** $DOWNLOADED"
              echo "- **Working Proxies:** 0"
            } >> $GITHUB_STEP_SUMMARY
          else
            {
              echo "## ❌ Download Failed"
              echo ""
              echo "Failed to download subscription data. Please check:"
              echo ""
              echo "1. Subscription URLs in \`sub.txt\`"
              echo "2. Network connectivity"
              echo "3. Subscription format validity"
            } >> $GITHUB_STEP_SUMMARY
          fi

      - name: Commit and push results
        if: success() && steps.test.outputs.working_count != '0'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add working_configs/
          if git diff --staged --quiet; then
            echo "📝 No changes to commit"
          else
            TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
            WORKING_COUNT="${{ steps.test.outputs.working_count }}"
            PROTOCOLS=$(python -c "
import sys,json
data=json.load(sys.stdin)
print(', '.join([f'{k}:{v}' for k,v in data['by_protocol'].items()]))
            " < working_configs/metadata.json)
            AVG_LATENCY=$(python -c "import sys,json;print(json.load(sys.stdin)['latency']['average'])" < working_configs/metadata.json)

            git commit -m "🔄 Update working configs – ${TIMESTAMP}" \
                       -m "" \
                       -m "📊 Statistics:" \
                       -m "- Working Proxies: ${WORKING_COUNT}" \
                       -m "- Average Latency: ${AVG_LATENCY}ms" \
                       -m "- Protocols: ${PROTOCOLS}" \
                       -m "" \
                       -m "Generated by automated testing workflow"
            git push
            echo "✅ Changes committed and pushed"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_number }}
          path: |
            working_configs/
            temp_configs/*.json
            temp_configs/*.txt
          retention-days: 7
          compression-level: 9

      - name: Upload working configs latest
        if: success() && steps.test.outputs.working_count != '0'
        uses: actions/upload-artifact@v4
        with:
          name: working-configs-latest
          path: |
            working_configs/all_working.txt
            working_configs/all_working_base64.txt
            working_configs/clash_config.yaml
            working_configs/metadata.json
          retention-days: 30

      - name: Create summary badge data
        if: always()
        run: |
          mkdir -p badges
          WORKING="${{ steps.test.outputs.working_count }}"
          TOTAL="${{ steps.download.outputs.proxy_count }}"
          if [ -n "$WORKING" ] && [ -n "$TOTAL" ] && [ "$TOTAL" != "0" ]; then
            SUCCESS_RATE=$(python -c "print(f'{($WORKING/$TOTAL*100):.1f}')")
            COLOR="green"
            MSG="$WORKING/$TOTAL ($SUCCESS_RATE%)"
          else
            COLOR="red"
            MSG="failed"
          fi
          echo "{\"schemaVersion\":1,\"label\":\"proxies\",\"message\":\"$MSG\",\"color\":\"$COLOR\"}" > badges/status.json
          cat badges/status.json

      - name: Clean up temporary files
        if: always()
        run: |
          rm -rf temp_configs/*.yaml temp_configs/config_*.yaml
          find temp_configs -name "test_config_*.yaml" -mtime +1 -delete 2>/dev/null || true
          echo "🧹 Cleanup complete"

      - name: Post-test validation
        if: success()
        run: |
          echo "🔍 Validating output files..."
          EXPECTED_FILES=(
            working_configs/working_proxies.json
            working_configs/all_working.txt
            working_configs/clash_config.yaml
            working_configs/metadata.json
          )
          MISSING=0
          for file in "${EXPECTED_FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing: $file"
              MISSING=$((MISSING + 1))
            else
              SIZE=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file" 2>/dev/null)
              echo "✅ $file (${SIZE} bytes)"
            fi
          done
          if [ $MISSING -gt 0 ]; then
            echo "⚠️  Warning: $MISSING expected files missing"
          else
            echo "✅ All output files validated"
          fi

      - name: Send notification on failure
        if: failure()
        run: echo "::warning::Clash config testing workflow failed. Please check the logs."
